version: '3.8'

services:
  facade-service:
    build:
      context: .
      dockerfile: facade_service/Dockerfile
    ports:
      - "8080:8000"
    depends_on:
      - logging-service
      - counter-service

  logging-service:
    build:
      context: .
      dockerfile: logging_service/Dockerfile
    ports:
      - "8081:8000"

  counter-service:
    build:
      context: .
      dockerfile: counter_service/Dockerfile
    ports:
      - "8082:8000"